#!/bin/bash

set -e
set -o pipefail

exec 3>&1
exec 1>&2

# Read inputs
payload=$(mktemp github-event-resource-request.XXXXXX)
cat > $payload <&0
payload_body=$(cat $payload)

resource=/opt/resource
cd $resource

result=$(mktemp github-event-resource-result.XXXXXX)
export RESULT_FILE_PATH=$resource/$result

npm cache clean --force
npm run --silent check $payload_body
echo $(cat $RESULT_FILE_PATH) >&3