#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
source=$1
payload=$(mktemp github-event-resource-request.XXXXXX)
cat > $payload <&0
payload_body=$(cat $payload)

cd /opt/resource
result=$(mktemp github-event-resource-result.XXXXXX)
export RESULT_FILE_PATH=$source/$result

npm cache clean --force
npm run --silent in $payload_body $source
echo $(cat $RESULT_FILE_PATH) >&3