#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
source=$1
payload=$(mktemp github-event-resource-request.XXXXXX)
cat > $payload <&0

node /opt/resource/lib/cmd/out.js $source $(cat $payload)